#server:
#  port: '8081'
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  datasource:
#    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/dcpapp'
#    username: root
#    password: rootadmin
#    driver-class-name: com.mysql.cj.jdbc.Driver
